theme = {}

--theme.font                  = 'MonteCarlo 8'
theme.font                  = 'snap 8'
theme.bg_normal             = '#000000'
theme.fg_normal             = '#888888'
theme.border_normal         = '#333333'
theme.bg_focus              = '#000000'
theme.fg_focus              = '#B1D631'
theme.border_focus          = '#74B073'
theme.bg_urgent             = '#000000'
theme.fg_urgent             = '#FFFFAF'
theme.bg_minimize           = '#222222'
theme.fg_minimize           = '#666666'
theme.border_width          = '2'
theme.border_marked         = '#B1D631'
theme.taglist_squares       = 'true'
theme.taglist_squares_sel   = '/usr/share/awesome/themes/default/taglist/squarefw.png'
theme.taglist_squares_unsel = '/usr/share/awesome/themes/default/taglist/squarew.png'
theme.titlebar_close_button = 'false'
theme.wallpaper_cmd         = {'feh --bg-scale /home/gig/walls/women/johansson1.jpg'}
theme.layout_floating       = '/home/gig/.config/awesome/icons/layouts/floating.png'
theme.layout_magnifier      = '/home/gig/.config/awesome/icons/layouts/magnifier.png'
theme.layout_max            = '/home/gig/.config/awesome/icons/layouts/max.png'
theme.layout_tilebottom     = '/home/gig/.config/awesome/icons/layouts/tilebottom.png'
theme.layout_tileleft       = '/home/gig/.config/awesome/icons/layouts/tileleft.png'
theme.layout_tile           = '/home/gig/.config/awesome/icons/layouts/tile.png'
theme.layout_tiletop        = '/home/gig/.config/awesome/icons/layouts/tiletop.png'

return theme
